/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockfunction2.h"

static const char* CMockString_start = "start";

typedef struct _CMOCK_start_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_start_CALL_INSTANCE;

static struct Mockfunction2Instance
{
  char start_IgnoreBool;
  char start_CallbackBool;
  CMOCK_start_CALLBACK start_CallbackFunctionPointer;
  int start_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE start_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockfunction2_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.start_CallInstance;
  if (Mock.start_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_start);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.start_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockfunction2_Init(void)
{
  Mockfunction2_Destroy();
}

void Mockfunction2_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void start(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_start_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_start);
  cmock_call_instance = (CMOCK_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.start_CallInstance);
  Mock.start_CallInstance = CMock_Guts_MemNext(Mock.start_CallInstance);
  if (Mock.start_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.start_CallbackBool &&
      Mock.start_CallbackFunctionPointer != NULL)
  {
    Mock.start_CallbackFunctionPointer(Mock.start_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.start_CallbackFunctionPointer != NULL)
  {
    Mock.start_CallbackFunctionPointer(Mock.start_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void start_CMockIgnore(void)
{
  Mock.start_IgnoreBool = (char)1;
}

void start_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_start_CALL_INSTANCE));
  CMOCK_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.start_CallInstance = CMock_Guts_MemChain(Mock.start_CallInstance, cmock_guts_index);
  Mock.start_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void start_AddCallback(CMOCK_start_CALLBACK Callback)
{
  Mock.start_IgnoreBool = (char)0;
  Mock.start_CallbackBool = (char)1;
  Mock.start_CallbackFunctionPointer = Callback;
}

void start_Stub(CMOCK_start_CALLBACK Callback)
{
  Mock.start_IgnoreBool = (char)0;
  Mock.start_CallbackBool = (char)0;
  Mock.start_CallbackFunctionPointer = Callback;
}

